### ISSUE TITLE
[solved]与产品模块冲突

### ISSUE THREAD

**Issue by fxiao** [buke/openerp-taobao#1]
安装完openerp-taobao后，产品模块显示不了单产品的信息（添没添加淘宝店的信息都一样），但编辑产品倒没问题。

安装应用模块有：
CRM
仓库管理
生产资源计划模块
采购管理
eInvoicing & Payments
openerp-taobao

操作流程：
销售（采购或仓库）--->  产品 ---> 产品 ---> 点击一个产品（非编辑）

**Comment by buke** [comment]
谢谢您的测试 ～

产品模块显示不了单产品的信息　　？？？　（不明白您要表达的意思，　没法重现您的错误）　

提交bug 的时候，请详细描述您的错误信息，以及OE版本、系统运行环境，如果需要请提供log 信息。 
还有最关键的就是 问题的重现方法。

谢谢 ～

**Comment by fxiao** [comment]
不好意思。。

服务器环境：
系统：debian 6.0.5
OE版本：6.1.1
PY版本：2.6.6

测试环境：
系统：mac osx 10.7.4
浏览器：safari 5.1.7 和 firefox 12.0

问题：安装完openerp-taobao后，在产品列表中点击查看产品的详细信息时，显示空白。。但编辑产品没问题。。
openerp-server.log 没有记录到异常情况；
浏览器（两个都是）也没有报错，并且已经加载了JSON的返回数据

重现操作流程（WEB）：

新建一个数据库（装入演示数据）；

安装以下应用模块：
CRM
仓库管理
生产资源计划模块
采购管理
eInvoicing & Payments
openerp-taobao；

之后点击：
销售（采购或仓库）---> 产品 ---> 产品 ---> 点击一个产品（非编辑）

谢谢！

**Comment by buke** [comment]
按照你的方法，可以重现该错误。

解决方法：（可能不需要第2、3步骤）
1、随便编辑一个产品，然后保存。
2、重启OE
3、清除浏览器缓存，重新登录即可解决。

原因：
未知。猜测是OE 在loading demo 数据是有缓存，没有更新缓存。

此问题可能属于OE DEMO问题，不是 openerp-taobao 模块问题。 此模块我在正常使用中，当然我没有load demo data，没有发现过类似问题。

谢谢您的测试 ～   

wangbuke@gmail.com   QQ: 17779104

**Comment by fxiao** [comment]
谢谢

解决方法：（可能不需要第2、3步骤）
1、随便编辑一个产品，然后保存。
2、重启OE
3、清除浏览器缓存，重新登录即可解决。

不需要第2步骤。1、3 一定要。。

再次感谢！

**Comment by buke** [comment]
已确认是  bug， 位于 https://github.com/buke/openerp-taobao/blob/master/taobao/taobao_product_view.xml 中  。 
现已修正，code 已经更新，请重新打包下载。谢谢 ～
