### ISSUE TITLE
安装的时候报完整性错误

### ISSUE THREAD

**Issue by wf141732** [buke/openerp-taobao#2]
完整性错误 

该操作无法完成，可能是由于以下原因：\n
- 删除：您可能会试图删除一个记录，但是仍有其它记录引用到它 \n
- 创建/更新：一个必须要输入的字段不正确

[对象及引用: categ_id - categ.id]

**Comment by buke** [comment]
提交bug 的时候，请详细描述您的错误信息，以及OE版本、系统运行环境，如果需要请提供log 信息。
还有最关键的就是 问题的重现方法。
