### ISSUE TITLE
taobao.user.get 的新接口

### ISSUE THREAD

**Issue by joshuajan** [buke/openerp-taobao#3]
根据新的taobao.user.get  调用权限http://api.taobao.com/apidoc/api.htm?path=cid:1-apiId:21349
在taobao_user.py的taobao.user.get 应该改成 taobao.user.buyer.get 
taobao_shop.py的taobao.user.get 对应 taobao.user.seller.get
不知道可否

**Comment by buke** [comment]
taobao.user.buyer.get  是查询自己作为买家的用户信息
taobao.user.seller.get 是查询自己作为卖家的用户信息

应用级输入参数中，都不能输入用户名作为查询条件，只能查询自己的信息。

所以应该是不行的。
